name: Trigger auto deployment for demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-AutoDeployTrigger-6d9cbb6e-5617-4a17-90f3-b5eda95eb58b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEMO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.DEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMO_REGISTRY_PASSWORD }}
          containerAppName: demo
          resourceGroup: kokelowo-containers
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


