name: Trigger auto deployment for s2c-test-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/s2c-test-demo-AutoDeployTrigger-79f12b64-c9cd-42da-93f4-c083a31c90e0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.S2CTESTDEMO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.S2CTESTDEMO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.S2CTESTDEMO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: kokelowo.azurecr.io
          registryUsername: ${{ secrets.S2CTESTDEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.S2CTESTDEMO_REGISTRY_PASSWORD }}
          containerAppName: s2c-test-demo
          resourceGroup: kokelowo-containers
          imageToBuild: kokelowo.azurecr.io/s2c-test-demo:${{ github.sha }}
          


